In [1]:
# TODO
# Neural network with 6 inputs
# Creating 6 inputs
# Add more inputs
# Use sentiment output as a priority indicator for neural network output
# 

# 2 MODELS - neural network and sentiment 

In [18]:
from sklearn.neural_network import MLPClassifier
from sklearn import datasets
import numpy as np

In [2]:
# Example data 
digits = datasets.load_digits()

In [6]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [7]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [29]:
num_inputs = digits.data.shape[1]
num_outputs = 1
num_hidden_neurons = (num_inp)

In [25]:
hidden_layer_sizes = (32,32)

In [22]:
classifier = MLPClassifier(hidden_layer_sizes=hidden_layer_sizes)

In [26]:
classifier.fit(digits.data, digits.target)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(65, 65), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [27]:
classifier.predict(digits.data)

array([0, 1, 2, ..., 8, 9, 8])